name: deploy flutter web to github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1
      - name: Checkout
        uses: actions/checkout@v4

      # 2
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3" # 최신 버전으로 설정

      # 3
      - name: Build web
        run: flutter build web --base-href "/${{ github.event.repository.name }}/"

      # 4
      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MUNGGYM }}
          publish_dir: ./build/web
